# Use root/example as user/password credentials
version: '3.1'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - b5478e381e29d6e063825f2a3dfc4aadf18e696c331bdba8e65b2b921d855c54:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: example

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    b5478e381e29d6e063825f2a3dfc4aadf18e696c331bdba8e65b2b921d855c54:
        external: true
